language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Te941smUJKyCDK1W6tTczLW2Df2wx/wMf0X6664iuXydvx7+Vj6FJBIAV1d+LjI5Y8Y0oT8Bdln/+zzfxARIJnHVPn58/pXKG4isTJLxyjuBR1v+79tbof6mtI7A97M6LHol+BlnHWdmKDXRjFYIbUsZO/zH41d14qcnetVEgkh9CoKtdvXJC5ppC42V1NXCkEMm1UQKU2mEssHgprssAF9M0qWGOBVSvAzZl6HbhdyaNS9HE4FpCqcNzPoWGdVotJy/mXdzq3Hg8gFzCra+0pmW4Gbx7DKzRac/BXzQMGv6jpxwZ43/FM4wtzART6jcmib6vKsJKERjCnkv67stqRPzPxxDcMrcJcOdeuBdZ66WWtKRfRrel8WHUVczTJz0n6HdIDsKHbDrwpn+hDz9TaO7V42GPur+I7mplCRGILOpLB+scxkHxyQI7YCFlKMLXs5px5Bbf/Txq4RDeyx2/FRinns7iNjOsZ/EDFGIAEbRmW1zLolv9j3+/zjpZ3jkMBqO1vmjn7Rs1+ixacciYE+peVdgNUyKeFc/5tlGct8tLFONhzVQknc4Rwcuih0Htcc/RX9legSg7tVrccCAQ+B0FZBa1Kg5DoQvqE9qEYXynZFjTaOttlGOE8qnggguX4Moy5+9iWEbRsKIKx+Hh8vVAmoe2Ec1PP5mSkMLW04="

matrix:
  include:
    - os: linux
      compiler: gcc
      env: Compiler_Version="default"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
      env: Tr_Compiler_Version="-5"
    - os: linux
      compiler: gcc
      before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-6
        coverity_scan:
          project:
            name: "theimpossibleastronaut/rmw"
            description: "a cross-platform command-line 'trash can' utility"
          notification_email: andy400-dev@yahoo.com
          build_command_prepend: "./configure"
          build_command: "make"
          branch_pattern: master
      env: Tr_Compiler_Version="-6"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-7
      env: Tr_Compiler_Version="-7"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-8
      env: Tr_Compiler_Version="-8"
    - os: linux
      compiler: clang
      addons:
          apt:
            packages:
            - libncurses5-dev
      env: BUILD=linux_clang
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
          packages:
          - clang-6.0
      env: Tr_Compiler_Version="-6.0"
    - os: osx
      osx_image: xcode9.3beta
      env: BUILD=osx_xcode9_3
    - os: osx
      osx_image: xcode9.2
      env: BUILD=osx_xcode9_2
  allow_failures:
  - os: osx

script:
  - export CXX=$CXX$Tr_Compiler_Version
  - export CC=$CC$Tr_Compiler_Version
  - ./configure --prefix=$PWD/temp-build
  - make
  - make install
  - cd test
  - ./basic.sh
  - rm -rf tmp-home
  - ./purging.sh
  - cd ..
  - make uninstall

notifications:
  slack: removetowaste:u16fiNsaMeLmg7J4WXifW3Zm
